### ISSUE TITLE
Recenter to selection

### ISSUE THREAD

**Issue by pjmclaughlin1979** [Esri/nearby-javascript#22] opened 2019-02-18 22:05 UTC
On larger screens with both the map and list of nearby places visible, the map will recenter and highlight the selected place, however, on smaller screens with only the list visible - if you select a place, the map opens but it doesn't highlight and recenter over the selected place.

**Comment by odoe** [comment] 2019-02-19 17:45
This is a duplicate of #20 which should be fixed now.

Thanks!

**Closed by odoe** 2019-02-19 17:45 UTC
Labels: Closed - Duplicate
